logging:
  level:
    org.springframework.integration: WARN

---
spring:
  profiles: source
  cloud:
    stream:
      bindings:
        output:
          destination: splitWindowAndCount-input
function:
  name: words

---
spring:
  profiles: processor
  cloud:
    stream:
      bindings:
        input:
          destination: splitWindowAndCount-input
          group: default
        output:
          destination: splitWindowAndCount-output
function:
  name: splitWindowAndCount

---
spring:
  profiles: sink
  cloud:
    stream:
      bindings:
        input:
          destination: splitWindowAndCount-output
          group: default
function:
  name: print
