logging:
  level:
    org.springframework.integration: WARN

---
spring:
  profiles: source
  cloud:
    stream:
      bindings:
        output:
          destination: splitWindowAndCount-input
server:
  port: 9001
function:
  name: words

---
spring:
  profiles: processor
  cloud:
    stream:
      bindings:
        input:
          destination: splitWindowAndCount-input
          group: default
        output:
          destination: splitWindowAndCount-output
server:
  port: 9002
function:
  name: splitWindowAndCount

---
spring:
  profiles: sink
  cloud:
    stream:
      bindings:
        input:
          destination: splitWindowAndCount-output
          group: default
server:
  port: 9003
function:
  name: print
